const axios = require("axios");

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const GEMINI_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`;

async function rankResultsWithGemini(query, results) {
  if (!Array.isArray(results)) {
    throw new Error("rankResultsWithGemini expects an array of results");
  }

  // Full prompt text with flexible ranking behavior
  const promptText = `
Given the user's search query: "${query}".

Rank the following search results based on their relevance and importance for research purposes.

Return the top 5 results and provide a short explanation for each, explaining why it's relevant to the query.

Results:
${results
  .map(
    (r, i) =>
      `${i + 1}. Title: ${r.title}\nSummary: ${r.summary || "No summary"}\nLink: ${r.link}`
  )
  .join("\n\n")}
`;

  try {
    const response = await axios.post(
      GEMINI_URL,
      {
        contents: [
          {
            parts: [
              {
                text: promptText,
              },
            ],
          },
        ],
      },
      {
        headers: {
          "Content-Type": "application/json",
        },
      }
    );

    const generatedText = response.data?.candidates?.[0]?.content?.text || "";

    console.log("Gemini response:\n", generatedText);
    console.log("Response generated successfully");

    // You can optionally parse Gemini output here.
    console.log(results);
    return results.slice(0, 5); // Placeholder logic until structured parsing is added.
  } catch (error) {
    console.error("Gemini ranking failed:", error.response?.data || error.message);
    return results;
  }
}

function cleanJsonString(str) {
  if (!str) return "";
  return str
    .trim()
    .replace(/^```json\s*/i, "")
    .replace(/^```/, "")
    .replace(/```$/, "")
    .trim();
}

async function getFiltersFromGemini(query) {
  if (!query) throw new Error("Query is required for getting filters.");

  const promptText = `
You are an AI assistant helping to refine search results. Given the user’s search query "${query}", suggest exactly 5 specific and relevant filter keywords that match the intent and context of the query. These keywords should be concrete terms or phrases (not broad categories) that can help narrow down the results. Tailor them to the query's subject.

Respond only with a plain JSON array of 5 strings, nothing else. Example:
["Java", "Beginner", "Spring Boot", "2024", "Online Course"]
`;

  try {
    const response = await axios.post(
      GEMINI_URL,
      {
        contents: [
          {
            parts: [
              {
                text: promptText,
              },
            ],
          },
        ],
      }
    );

    let generatedText = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      console.warn("No text generated by Gemini.");
      return [];
    }

    // Clean the text from markdown code fences
    generatedText = cleanJsonString(generatedText);

    console.log("Cleaned text for JSON parsing:", generatedText);

    try {
      const filters = JSON.parse(generatedText);
      if (Array.isArray(filters)) {
        console.log("Parsed filters:", filters);
        return filters.slice(0, 5);
      } else {
        console.warn("Parsed JSON is not an array.");
        return [];
      }
    } catch (parseError) {
      console.error("JSON parse error:", parseError.message);
      return [];
    }
  } catch (err) {
    console.error("Gemini API call failed:", err.message);
    return [];
  }
}

module.exports = {
  rankResultsWithGemini, getFiltersFromGemini,
};
